title: Dum3bi
url: http://dum3bi.com
description: Dumebi Iwuchukwu is an Art Director, Brand Strategist and Developer based in Lagos, Nigeria.

collections:
  portfolio:

markdown: kramdown

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
