[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy= "no-referrer"
    X-Content-Type-Options= "nosniff"

    #  Multi-value headers are expressed with multi-line strings
	cache-control = '''
	max-age=31536000,
	no-cache,
	no-store,
  public,
	must-revalidate'''
  Content-Language= "en"

  [[redirects]]
    from = "/*"
    to = "/404.html"
    status = 404
    force = true
